name: Request review on PRs

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: actions/github-script@v7
        env:
          REVIEWERS: "stevoland"
        with:
          script: |
            console.log(github.rest)
            console.log(github.rest.pulls)
            const pull_number = context.payload.pull_number
            const token = process.env.GITHUB_TOKEN
            const reviewers = process.env.REVIEWERS && process.env.REVIEWERS.split(',')
            const team_reviewers = process.env.TEAM_REVIEWERS && process.env.TEAM_REVIEWERS.split(',')

            const response = await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number,
              reviewers,
              team_reviewers,
              token
            })

            console.log(response)
