name: Request review on PRs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: actions/github-script@v2
        env:
          REVIEWERS: "stevoland"
        with:
          script: |
            const team = 'stevoland';
            const token = process.env.GITHUB_TOKEN;

            const response = await github.rest.pulls.addReviewers({
              pull_id: context.payload.pull_id,
              // team_reviewers: [team],
              reviewers: fromJSON(`${process.env.REVIEWERS}`)
              token
            });

            console.log(response);
