name: Request review on PRs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: ubuntu-20.04

    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.PR_REVIEWERS }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer stevoland
