name: Request review on PRs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: actions/github-script@v7
        env:
          REVIEWERS: "stevoland"
        with:
          script: |
            const pull_id = context.payload.pull_id
            const token = process.env.GITHUB_TOKEN
            const reviewers = process.env.REVIEWERS && JSON.parse(`[${process.env.REVIEWERS}]`)
            const team_reviewers = process.env.REVIEWERS && JSON.parse(`[${process.env.TEAM_REVIEWERS}]`)

            const response = await github.rest.pulls.addReviewers({
              pull_id,
              reviewers,
              team_reviewers,
              token
            })

            console.log(response)
